This is the vagrant configuration used to produce the 2.6 beta 1 builds of MapGuide for Ubuntu and CentOS
git-svn-id: http://svn.osgeo.org/mapguide/branches/2.6@8125 a442ad82-b40c-0410-ae44-e6d7bd6e4a36

diff --git a/vagrant/centos/x64/Vagrantfile b/vagrant/centos/x64/Vagrantfile
--- a/vagrant/centos/x64/Vagrantfile
+++ b/vagrant/centos/x64/Vagrantfile
@@ -126,6 +126,14 @@ check_build()
 		exit $error
 	fi
 }
+check_test()
+{
+	error=$?
+	if [ $error -ne 0 ]; then
+		echo "[warning]: ${BUILD_COMPONENT} - Unit Tests failed ($error)"
+		echo "[warning]: ${BUILD_COMPONENT} - Unit Tests failed ($error)" >> ~/unit_test_status.log
+	fi
+}
 if hash scons 2>/dev/null; then
 	echo [provision]: We have scons
 else
@@ -140,12 +148,18 @@ HAVE_FDO=0
 HAVE_FDO_LIBS=0
 HAVE_MAPGUIDE=0
 MG_UNIT_TEST=0
+FDO_UNIT_TEST=0
 SCRIPT_ROOT=~/scripts
-FDO_SRC_ROOT=~/fdo
-FDO_SRC=$FDO_SRC_ROOT/trunk
+FDO_SRC_ROOT=~/fdo/branches
+FDO_VER_MM=3.9
+MG_VER_MM=2.6
+FDO_SRC_DIR=3.9
+FDO_SRC=$FDO_SRC_ROOT/$FDO_SRC_DIR
 FDO_LIB_SRC=~/fdo_rdbms_thirdparty
-MG_SRC_ROOT=~/mapguide/trunk
+MG_SRC_ROOT=~/mapguide/branches/2.6
 MG_SRC=$MG_SRC_ROOT/MgDev
+FDO_TARBALL=fdo-checkout-3.9.tar.gz
+MG_TARBALL=mapguide-checkout-2.6.tar.gz
 if [ -d $FDO_SRC ]; 
 then
     HAVE_FDO=1
@@ -158,8 +172,8 @@ if [ -d $MG_SRC ];
 then
     HAVE_MAPGUIDE=1
 fi
-echo [provision]: Checking all tools and libs are in place
-yum install -y gcc-* gd-* automake bison byacc flex doxygen expat expat-devel libtool libjpeg-devel libpng libpng-devel libxml2 libxml2-devel openssl curl curl-devel libxslt libxslt-devel subversion java-1.7.0-openjdk java-1.7.0-openjdk-devel ant dos2unix openssh-server openldap-devel alsa-lib-devel pcre-devel unixODBC-devel libcom_err-devel krb5-devel openssl-devel mysql-devel postgresql-devel unixODBC
+#echo [provision]: Checking all tools and libs are in place
+#yum install -y gcc-* gd-* automake bison byacc flex doxygen expat expat-devel libtool libjpeg-devel libpng libpng-devel libxml2 libxml2-devel openssl curl curl-devel libxslt libxslt-devel subversion java-1.7.0-openjdk java-1.7.0-openjdk-devel ant dos2unix openssh-server openldap-devel alsa-lib-devel pcre-devel unixODBC-devel libcom_err-devel krb5-devel openssl-devel mysql-devel postgresql-devel unixODBC
 echo [provision]: Copying shell scripts
 mkdir -p $SCRIPT_ROOT
 cp -f /vagrant/*.sh $SCRIPT_ROOT
@@ -179,15 +193,15 @@ then
 fi
 if [ $HAVE_FDO -eq 0 ];
 then
-    echo [provision]: Extracting FDO trunk working copy
-    mkdir -p ~/fdo
-    tar -zxf /mapguide_sources/fdo-checkout.tar.gz -C ~/fdo
+    echo [provision]: Extracting FDO working copy
+    mkdir -p $FDO_SRC_ROOT
+    tar -zxf /mapguide_sources/$FDO_TARBALL -C $FDO_SRC_ROOT
 fi
 if [ $HAVE_MAPGUIDE -eq 0 ];
 then
-    echo [provision]: Extracting MapGuide trunk working copy
+    echo [provision]: Extracting MapGuide working copy
     mkdir -p $MG_SRC_ROOT
-    tar -zxf /mapguide_sources/mapguide-checkout.tar.gz -C $MG_SRC_ROOT
+    tar -zxf /mapguide_sources/$MG_TARBALL -C $MG_SRC_ROOT
 fi
 echo [provision]: svn update FDO
 BUILD_COMPONENT="svn update FDO"
@@ -207,6 +221,8 @@ then
     echo [provision]: Applying MapGuide source patches
     cp -R /mapguide_sources/patches/mapguide/* $MG_SRC
 fi
+echo [provision]: Making sure swig is executable
+chmod +x $MG_SRC/Oem/SWIGEx/Linux/swig
 cd ~/scripts
 BUILD_COMPONENT="FDO"
 sudo -E ./build_fdo.sh 2>&1 | tee ~/fdo_build.log
@@ -214,27 +230,64 @@ check_build
 BUILD_COMPONENT="MapGuide"
 sudo -E ./build.sh 2>&1 | tee ~/mapguide_build.log
 check_build
+FDO_REV=`svn info $FDO_SRC | perl revnum.pl`
+MG_REV=`svn info $MG_SRC | perl revnum.pl`
+> ~/unit_test_status.log
+if [ $FDO_UNIT_TEST -eq 1 ];
+then
+    echo [provision]: Unit test FDO
+    BUILD_COMPONENT="Unit Test FDO Core"
+    cd $SCRIPT_ROOT/fdo_build_area/Fdo/UnitTest
+    sudo ./UnitTest 2>&1 | tee ~/fdo_core_unit_test.log
+    check_test
+    BUILD_COMPONENT="Unit Test SHP Provider"
+    cd $SCRIPT_ROOT/fdo_build_area/Providers/SHP/Src/UnitTest
+    sudo ./UnitTest 2>&1 | tee ~/fdo_shp_unit_test.log
+    check_test
+    BUILD_COMPONENT="Unit Test SDF Provider"
+    cd $SCRIPT_ROOT/fdo_build_area/Providers/SDF/Src/UnitTest
+    sudo ./UnitTest 2>&1 | tee ~/fdo_sdf_unit_test.log
+    check_test
+    BUILD_COMPONENT="Unit Test SQLite Provider"
+    cd $SCRIPT_ROOT/fdo_build_area/Providers/SQLite/Src/UnitTest
+    sudo ./UnitTest 2>&1 | tee ~/fdo_sqlite_unit_test.log
+    check_test
+    BUILD_COMPONENT="Unit Test GDAL Provider"
+    cd $SCRIPT_ROOT/fdo_build_area/Providers/GDAL/Src/UnitTest
+    sudo ./UnitTest 2>&1 | tee ~/fdo_gdal_unit_test.log
+    check_test
+    BUILD_COMPONENT="Unit Test WMS Provider"
+    cd $SCRIPT_ROOT/fdo_build_area/Providers/WMS/Src/UnitTest
+    sudo ./UnitTest 2>&1 | tee ~/fdo_wms_unit_test.log
+    check_test
+fi
 if [ $MG_UNIT_TEST -eq 1 ];
 then
     echo [provision]: Unit test MapGuide
+    BUILD_COMPONENT="Unit Test MapGuide Server"
     cd $SCRIPT_ROOT/mgdev
     sudo make check 2>&1 | tee ~/mapguide_unit_test.log
+    check_test
 fi
 cd $SCRIPT_ROOT
 sudo mkdir -p /vagrant/build
 sudo mv -f ~/*.log /vagrant/build
 sudo cp bin/*.tar.gz /vagrant/build
 sudo cp fdosdk*.tar.gz /vagrant/build
+sudo cp ~/unit_test_status.log /vagrant/build/unit_test_status.log
+sudo cp /vagrant/mginstallcentos.sh /vagrant/build/mginstallcentos.sh
+sudo sed -i 's/FDOVER_REV=0/FDOVER_REV='"$FDO_REV"'/g' /vagrant/build/mginstallcentos.sh
+sudo sed -i 's/MGVER_REV=0/MGVER_REV='"$MG_REV"'/g' /vagrant/build/mginstallcentos.sh
 if [ ! -d /mapguide_sources/updated ]; then
     sudo mkdir -p /mapguide_sources/updated
-    cd ~/mapguide/trunk
+    cd $MG_SRC_ROOT
     echo [provision]: Updating mapguide source tarball
-    tar -zcf mapguide-checkout.tar.gz MgDev
-    sudo mv mapguide-checkout.tar.gz /mapguide_sources/updated
-    cd ~/fdo
+    tar -zcf $MG_TARBALL MgDev
+    sudo mv $MG_TARBALL /mapguide_sources/updated
+    cd $FDO_SRC_ROOT
     echo [provision]: Updating fdo source tarball
-    tar -zcf fdo-checkout.tar.gz trunk
-    sudo mv fdo-checkout.tar.gz /mapguide_sources/updated
+    tar -zcf $FDO_TARBALL $FDO_SRC_DIR
+    sudo mv $FDO_TARBALL /mapguide_sources/updated
 else
     echo [provision]: Updated tarballs already exist. Doing nothing
 fi
